# Generated by Django 5.2 on 2025-05-04 18:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_remove_customuser_phone_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["username"],
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to.",
                related_name="custom_user_set",
                related_query_name="custom_user",
                to="auth.group",
                verbose_name="groupes",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="location",
            field=models.CharField(blank=True, max_length=100, verbose_name="Lieu"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("CLIENT", "Client"),
                    ("LIVREUR", "Livreur"),
                    ("EMPLOYE", "Employé"),
                    ("ADMIN", "Admin"),
                ],
                default="CLIENT",
                max_length=10,
                verbose_name="Rôle",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="custom_user_set",
                related_query_name="custom_user",
                to="auth.permission",
                verbose_name="permissions utilisateur",
            ),
        ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=100, verbose_name="Prénom")),
                ("adresse", models.TextField(verbose_name="Adresse")),
                (
                    "solde_de_credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="Solde de crédit",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Client",
                "verbose_name_plural": "Profils Clients",
                "ordering": ["user__username"],
            },
        ),
    ]
