name: binmax_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_swiper_null_safety: ^1.0.2
  card_swiper: ^3.0.1
  provider: ^6.0.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

