# Generated by Django 5.2 on 2025-05-14 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("entrepot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom du Fournisseur"),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Contact"
                    ),
                ),
                ("adresse", models.TextField(blank=True, verbose_name="Adresse")),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
            },
        ),
        migrations.CreateModel(
            name="Palette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Référence",
                    ),
                ),
                ("date_ajout", models.DateField(verbose_name="Date d'ajout")),
                (
                    "prix_achat",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix d'achat"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "categories",
                    models.CharField(
                        blank=True,
                        help_text="Enter categories separated by commas",
                        max_length=200,
                        verbose_name="Catégories",
                    ),
                ),
                (
                    "entrepot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="palettes",
                        to="entrepot.entrepot",
                        verbose_name="Entrepôt",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="palettes",
                        to="palettes.fournisseur",
                        verbose_name="Fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Palette",
                "verbose_name_plural": "Palettes",
                "ordering": ["-date_ajout"],
            },
        ),
    ]
