# Generated by Django 5.2 on 2025-05-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Palette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Référence",
                    ),
                ),
                ("date_ajout", models.DateField(verbose_name="Date d'ajout")),
                (
                    "prix_achat",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix d'achat"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
            ],
            options={
                "verbose_name": "Palette",
                "verbose_name_plural": "Palettes",
                "ordering": ["-date_ajout"],
            },
        ),
    ]
