# Generated by Django 5.2 on 2025-05-06 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("palettes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom du Fournisseur"),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Contact"
                    ),
                ),
                ("adresse", models.TextField(blank=True, verbose_name="Adresse")),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
            },
        ),
        migrations.AddField(
            model_name="palette",
            name="categories",
            field=models.CharField(
                blank=True,
                help_text="Enter categories separated by commas",
                max_length=200,
                verbose_name="Catégories",
            ),
        ),
        migrations.AddField(
            model_name="palette",
            name="fournisseur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="palettes",
                to="palettes.fournisseur",
                verbose_name="Fournisseur",
            ),
        ),
    ]
