# Generated by Django 5.2 on 2025-05-14 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entrepot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("adresse", models.TextField(blank=True, verbose_name="Adresse")),
            ],
            options={
                "verbose_name": "Entrepôt",
                "verbose_name_plural": "Entrepôts",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="Code")),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "entrepot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zones",
                        to="entrepot.entrepot",
                        verbose_name="Entrepôt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone",
                "verbose_name_plural": "Zones",
                "ordering": ["entrepot__code", "code"],
                "unique_together": {("entrepot", "code")},
            },
        ),
        migrations.CreateModel(
            name="Rayon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="Code")),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "emplacement_limit",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Limite d'emplacements"
                    ),
                ),
                (
                    "emplacement_used",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Emplacements utilisés"
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rayons",
                        to="entrepot.zone",
                        verbose_name="Zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rayon",
                "verbose_name_plural": "Rayons",
                "ordering": ["zone__entrepot__code", "zone__code", "code"],
                "unique_together": {("zone", "code")},
            },
        ),
    ]
