# Generated by Django 5.2 on 2025-05-14 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="client",
            field=models.ForeignKey(
                limit_choices_to={"role": "CLIENT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.cart",
                verbose_name="Panier",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="main_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.productimage",
                verbose_name="Image principale",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="products.product",
                verbose_name="Produit",
            ),
        ),
        migrations.AddField(
            model_name="clientorderhistory",
            name="client",
            field=models.ForeignKey(
                limit_choices_to={"role": "CLIENT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_history",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="deliveryslip",
            name="employee",
            field=models.ForeignKey(
                limit_choices_to={"role": "EMPLOYE"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_slips",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Employé",
            ),
        ),
        migrations.AddField(
            model_name="employeedeliveryhistory",
            name="delivery_slip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.deliveryslip",
                verbose_name="Bon de commande",
            ),
        ),
        migrations.AddField(
            model_name="employeedeliveryhistory",
            name="employee",
            field=models.ForeignKey(
                limit_choices_to={"role": "EMPLOYE"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_history",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Employé",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                limit_choices_to={"role": "CLIENT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Client",
            ),
        ),
        migrations.AddField(
            model_name="deliveryslip",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_slip",
                to="orders.order",
                verbose_name="Commande",
            ),
        ),
        migrations.AddField(
            model_name="clientorderhistory",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
                verbose_name="Commande",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
                verbose_name="Commande",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="products.product",
                verbose_name="Produit",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "product")},
        ),
    ]
