# Generated by Django 5.2 on 2025-05-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryslip",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("PREPARED", "Préparé"),
                    ("SHIPPED", "Expédié"),
                    ("DELIVERED", "Livré"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
