# Generated by Django 5.2 on 2025-05-12 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_deliveryslip_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliveryslip",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Bon de commande",
                "verbose_name_plural": "Bons de commande",
            },
        ),
        migrations.AlterField(
            model_name="employeedeliveryhistory",
            name="delivery_slip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.deliveryslip",
                verbose_name="Bon de commande",
            ),
        ),
    ]
