# Generated by Django 5.2 on 2025-05-02 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("palettes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Emplacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="Code")),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
            ],
            options={
                "verbose_name": "Emplacement",
                "verbose_name_plural": "Emplacements",
                "ordering": ["rayon__zone__code", "rayon__code", "code"],
            },
        ),
        migrations.CreateModel(
            name="Rayon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="Code")),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "emplacement_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'emplacements"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rayon",
                "verbose_name_plural": "Rayons",
                "ordering": ["zone__code", "code"],
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
            ],
            options={
                "verbose_name": "Zone",
                "verbose_name_plural": "Zones",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        unique=True,
                        verbose_name="Référence",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantité")),
                (
                    "vendus",
                    models.PositiveIntegerField(default=0, verbose_name="Vendus"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.category",
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "emplacement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.emplacement",
                        verbose_name="Emplacement",
                    ),
                ),
                (
                    "palette",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="palettes.palette",
                        verbose_name="Palette",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
                "ordering": ["reference"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/", verbose_name="Image"),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Image principale"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image de produit",
                "verbose_name_plural": "Images de produit",
                "ordering": ["-is_main"],
            },
        ),
        migrations.AddField(
            model_name="emplacement",
            name="rayon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="emplacements",
                to="products.rayon",
                verbose_name="Rayon",
            ),
        ),
        migrations.AddField(
            model_name="rayon",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rayons",
                to="products.zone",
                verbose_name="Zone",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emplacement",
            unique_together={("rayon", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="rayon",
            unique_together={("zone", "code")},
        ),
    ]
