# Generated by Django 5.2 on 2025-05-14 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entrepot", "0001_initial"),
        ("palettes", "0001_initial"),
        ("products", "0002_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["entrepot__code", "code"],
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["reference"],
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
            },
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["-is_main"],
                "verbose_name": "Image de produit",
                "verbose_name_plural": "Images de produit",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.CharField(max_length=10, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="category",
            name="entrepot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="entrepot.entrepot",
                verbose_name="Entrepôt",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="products.category",
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="product",
            name="palette",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="palettes.palette",
                verbose_name="Palette",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Prix",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Quantité"),
        ),
        migrations.AlterField(
            model_name="product",
            name="rayon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="entrepot.rayon",
                verbose_name="Rayon",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="reference",
            field=models.CharField(
                editable=False, max_length=100, unique=True, verbose_name="Référence"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="vendus",
            field=models.PositiveIntegerField(default=0, verbose_name="Vendus"),
        ),
        migrations.AlterField(
            model_name="product",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="entrepot.zone",
                verbose_name="Zone",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="Image principale"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
                verbose_name="Produit",
            ),
        ),
    ]
