# Generated by Django 5.2 on 2025-05-14 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricingconfiguration",
            options={
                "verbose_name": "Configuration des Prix",
                "verbose_name_plural": "Configurations des Prix",
            },
        ),
    ]
