# Generated by Django 5.2 on 2025-05-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_pricingconfiguration_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_at_creation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Prix à la création",
            ),
        ),
    ]
