# Generated by Django 5.2 on 2025-05-14 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_price_at_creation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricingconfiguration",
            options={
                "verbose_name": "Configuration des Prix",
                "verbose_name_plural": "Configuration des Prix",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="price_at_creation",
        ),
    ]
