# Generated by Django 5.2 on 2025-05-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_pricingconfiguration_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricingconfiguration",
            options={
                "verbose_name": "Configuration des Prix",
                "verbose_name_plural": "Configurations des Prix",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="price_at_creation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Prix à la création",
            ),
        ),
    ]
