# Generated by Django 5.2 on 2025-05-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_pricingconfiguration_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="emplacement_freed",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Emplacement libéré"
            ),
        ),
    ]
